# vim: set ts=2 sw=2 sts=2 et:
#
# Unused config options
#
# @author    Qualiteam software Ltd <info@x-cart.com>
# @copyright Copyright (c) 2011-2013 Qualiteam software Ltd <info@x-cart.com>. All rights reserved
# @license   http://www.x-cart.com/license-agreement.html X-Cart 5 License Agreement
# @link      http://www.x-cart.com/

XLite\Model\Config:
  - { name: 'enable_anon_checkout', category: 'General' }
  - { name: 'show_thumbnails', category: 'General' }
  - { name: 'order_starting_number', category: 'General' }
