<?php

namespace XLite\Model\Proxy\__CG__\XLite\Model\AttributeValue;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class AttributeValueCheckbox extends \XLite\Model\AttributeValue\AttributeValueCheckbox implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setValue($value)
    {
        $this->__load();
        return parent::setValue($value);
    }

    public function asString()
    {
        $this->__load();
        return parent::asString();
    }

    public function getValue()
    {
        $this->__load();
        return parent::getValue();
    }

    public function setPriceModifier($priceModifier)
    {
        $this->__load();
        return parent::setPriceModifier($priceModifier);
    }

    public function getPriceModifier()
    {
        $this->__load();
        return parent::getPriceModifier();
    }

    public function setPriceModifierType($priceModifierType)
    {
        $this->__load();
        return parent::setPriceModifierType($priceModifierType);
    }

    public function getPriceModifierType()
    {
        $this->__load();
        return parent::getPriceModifierType();
    }

    public function setWeightModifier($weightModifier)
    {
        $this->__load();
        return parent::setWeightModifier($weightModifier);
    }

    public function getWeightModifier()
    {
        $this->__load();
        return parent::getWeightModifier();
    }

    public function setWeightModifierType($weightModifierType)
    {
        $this->__load();
        return parent::setWeightModifierType($weightModifierType);
    }

    public function getWeightModifierType()
    {
        $this->__load();
        return parent::getWeightModifierType();
    }

    public function setDefaultValue($defaultValue)
    {
        $this->__load();
        return parent::setDefaultValue($defaultValue);
    }

    public function getDefaultValue()
    {
        $this->__load();
        return parent::getDefaultValue();
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setProduct(\XLite\Model\Product $product = NULL)
    {
        $this->__load();
        return parent::setProduct($product);
    }

    public function getProduct()
    {
        $this->__load();
        return parent::getProduct();
    }

    public function setAttribute(\XLite\Model\Attribute $attribute = NULL)
    {
        $this->__load();
        return parent::setAttribute($attribute);
    }

    public function getAttribute()
    {
        $this->__load();
        return parent::getAttribute();
    }

    public function setModifier($value, $field)
    {
        $this->__load();
        return parent::setModifier($value, $field);
    }

    public function isDefault()
    {
        $this->__load();
        return parent::isDefault();
    }

    public function getAbsoluteValue($field)
    {
        $this->__load();
        return parent::getAbsoluteValue($field);
    }

    public function getFormatedValue($field)
    {
        $this->__load();
        return parent::getFormatedValue($field);
    }

    public function getModifier($field)
    {
        $this->__load();
        return parent::getModifier($field);
    }

    public function cloneEntity()
    {
        $this->__load();
        return parent::cloneEntity();
    }

    public function map(array $data)
    {
        $this->__load();
        return parent::map($data);
    }

    public function __get($name)
    {
        $this->__load();
        return parent::__get($name);
    }

    public function __set($name, $value)
    {
        $this->__load();
        return parent::__set($name, $value);
    }

    public function __isset($name)
    {
        $this->__load();
        return parent::__isset($name);
    }

    public function __unset($name)
    {
        $this->__load();
        return parent::__unset($name);
    }

    public function getRepository()
    {
        $this->__load();
        return parent::getRepository();
    }

    public function checkCache()
    {
        $this->__load();
        return parent::checkCache();
    }

    public function detach()
    {
        $this->__load();
        return parent::detach();
    }

    public function __call($method, array $args = array (
))
    {
        $this->__load();
        return parent::__call($method, $args);
    }

    public function setterProperty($property, $value)
    {
        $this->__load();
        return parent::setterProperty($property, $value);
    }

    public function getterProperty($property)
    {
        $this->__load();
        return parent::getterProperty($property);
    }

    public function isPersistent()
    {
        $this->__load();
        return parent::isPersistent();
    }

    public function isDetached()
    {
        $this->__load();
        return parent::isDetached();
    }

    public function getUniqueIdentifierName()
    {
        $this->__load();
        return parent::getUniqueIdentifierName();
    }

    public function getUniqueIdentifier()
    {
        $this->__load();
        return parent::getUniqueIdentifier();
    }

    public function update()
    {
        $this->__load();
        return parent::update();
    }

    public function create()
    {
        $this->__load();
        return parent::create();
    }

    public function delete()
    {
        $this->__load();
        return parent::delete();
    }

    public function processFiles($field, array $data)
    {
        $this->__load();
        return parent::processFiles($field, $data);
    }

    public function prepareEntityBeforeCommit($type)
    {
        $this->__load();
        return parent::prepareEntityBeforeCommit($type);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'value', 'priceModifier', 'priceModifierType', 'weightModifier', 'weightModifierType', 'defaultValue', 'id', 'product', 'attribute');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}