<?php

namespace XLite\Model\Proxy\__CG__\XLite\Module\XC\CanadaPost\Model\ProductsReturn;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Link extends \XLite\Module\XC\CanadaPost\Model\ProductsReturn\Link implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setReturn(\XLite\Module\XC\CanadaPost\Model\ProductsReturn $return = NULL)
    {
        $this->__load();
        return parent::setReturn($return);
    }

    public function setStorage(\XLite\Module\XC\CanadaPost\Model\ProductsReturn\Link\Storage $storage)
    {
        $this->__load();
        return parent::setStorage($storage);
    }

    public function getFileName()
    {
        $this->__load();
        return parent::getFileName();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setRel($rel)
    {
        $this->__load();
        return parent::setRel($rel);
    }

    public function getRel()
    {
        $this->__load();
        return parent::getRel();
    }

    public function setHref($href)
    {
        $this->__load();
        return parent::setHref($href);
    }

    public function getHref()
    {
        $this->__load();
        return parent::getHref();
    }

    public function setIdx($idx)
    {
        $this->__load();
        return parent::setIdx($idx);
    }

    public function getIdx()
    {
        $this->__load();
        return parent::getIdx();
    }

    public function setMediaType($mediaType)
    {
        $this->__load();
        return parent::setMediaType($mediaType);
    }

    public function getMediaType()
    {
        $this->__load();
        return parent::getMediaType();
    }

    public function getReturn()
    {
        $this->__load();
        return parent::getReturn();
    }

    public function getStorage()
    {
        $this->__load();
        return parent::getStorage();
    }

    public function getLinkTitle()
    {
        $this->__load();
        return parent::getLinkTitle();
    }

    public function getURL()
    {
        $this->__load();
        return parent::getURL();
    }

    public function getGetterURL()
    {
        $this->__load();
        return parent::getGetterURL();
    }

    public function getApiCallErrors()
    {
        $this->__load();
        return parent::getApiCallErrors();
    }

    public function callApiGetArtifact($flushChanges = false)
    {
        $this->__load();
        return parent::callApiGetArtifact($flushChanges);
    }

    public function map(array $data)
    {
        $this->__load();
        return parent::map($data);
    }

    public function __get($name)
    {
        $this->__load();
        return parent::__get($name);
    }

    public function __set($name, $value)
    {
        $this->__load();
        return parent::__set($name, $value);
    }

    public function __isset($name)
    {
        $this->__load();
        return parent::__isset($name);
    }

    public function __unset($name)
    {
        $this->__load();
        return parent::__unset($name);
    }

    public function getRepository()
    {
        $this->__load();
        return parent::getRepository();
    }

    public function checkCache()
    {
        $this->__load();
        return parent::checkCache();
    }

    public function detach()
    {
        $this->__load();
        return parent::detach();
    }

    public function __call($method, array $args = array (
))
    {
        $this->__load();
        return parent::__call($method, $args);
    }

    public function setterProperty($property, $value)
    {
        $this->__load();
        return parent::setterProperty($property, $value);
    }

    public function getterProperty($property)
    {
        $this->__load();
        return parent::getterProperty($property);
    }

    public function isPersistent()
    {
        $this->__load();
        return parent::isPersistent();
    }

    public function isDetached()
    {
        $this->__load();
        return parent::isDetached();
    }

    public function getUniqueIdentifierName()
    {
        $this->__load();
        return parent::getUniqueIdentifierName();
    }

    public function getUniqueIdentifier()
    {
        $this->__load();
        return parent::getUniqueIdentifier();
    }

    public function update()
    {
        $this->__load();
        return parent::update();
    }

    public function create()
    {
        $this->__load();
        return parent::create();
    }

    public function delete()
    {
        $this->__load();
        return parent::delete();
    }

    public function processFiles($field, array $data)
    {
        $this->__load();
        return parent::processFiles($field, $data);
    }

    public function cloneEntity()
    {
        $this->__load();
        return parent::cloneEntity();
    }

    public function prepareEntityBeforeCommit($type)
    {
        $this->__load();
        return parent::prepareEntityBeforeCommit($type);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'rel', 'href', 'idx', 'mediaType', 'return', 'storage');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}