<?php

namespace XLite\Model\Proxy\__CG__\XLite\Model;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Module extends \XLite\Model\Module implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function getMainClass()
    {
        $this->__load();
        return parent::getMainClass();
    }

    public function callModuleMethod($method, $result = NULL, array $args = array (
))
    {
        $this->__load();
        return parent::callModuleMethod($method, $result, $args);
    }

    public function getActualName()
    {
        $this->__load();
        return parent::getActualName();
    }

    public function getVersion()
    {
        $this->__load();
        return parent::getVersion();
    }

    public function hasIcon()
    {
        $this->__load();
        return parent::hasIcon();
    }

    public function getSettingsForm()
    {
        $this->__load();
        return parent::getSettingsForm();
    }

    public function getDependencyModules($onlyDisabled = false)
    {
        $this->__load();
        return parent::getDependencyModules($onlyDisabled);
    }

    public function getDependentModules()
    {
        $this->__load();
        return parent::getDependentModules();
    }

    public function canDisable()
    {
        $this->__load();
        return parent::canDisable();
    }

    public function isFree()
    {
        $this->__load();
        return parent::isFree();
    }

    public function isPurchased()
    {
        $this->__load();
        return parent::isPurchased();
    }

    public function isAvailable()
    {
        $this->__load();
        return parent::isAvailable();
    }

    public function isCustom()
    {
        $this->__load();
        return parent::isCustom();
    }

    public function getLicenseKey()
    {
        $this->__load();
        return parent::getLicenseKey();
    }

    public function getCurrency()
    {
        $this->__load();
        return parent::getCurrency();
    }

    public function isInstalled()
    {
        $this->__load();
        return parent::isInstalled();
    }

    public function getIdentityData()
    {
        $this->__load();
        return parent::getIdentityData();
    }

    public function getMarketplaceID()
    {
        $this->__load();
        return parent::getMarketplaceID();
    }

    public function isTranslation()
    {
        $this->__load();
        return parent::isTranslation();
    }

    public function hasLicenseRestriction()
    {
        $this->__load();
        return parent::hasLicenseRestriction();
    }

    public function prepareBeforeUpdate()
    {
        $this->__load();
        return parent::prepareBeforeUpdate();
    }

    public function getModuleID()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["moduleID"];
        }
        $this->__load();
        return parent::getModuleID();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setAuthor($author)
    {
        $this->__load();
        return parent::setAuthor($author);
    }

    public function getAuthor()
    {
        $this->__load();
        return parent::getAuthor();
    }

    public function setAuthorEmail($authorEmail)
    {
        $this->__load();
        return parent::setAuthorEmail($authorEmail);
    }

    public function getAuthorEmail()
    {
        $this->__load();
        return parent::getAuthorEmail();
    }

    public function setEnabled($enabled)
    {
        $this->__load();
        return parent::setEnabled($enabled);
    }

    public function getEnabled()
    {
        $this->__load();
        return parent::getEnabled();
    }

    public function setInstalled($installed)
    {
        $this->__load();
        return parent::setInstalled($installed);
    }

    public function getInstalled()
    {
        $this->__load();
        return parent::getInstalled();
    }

    public function setYamlLoaded($yamlLoaded)
    {
        $this->__load();
        return parent::setYamlLoaded($yamlLoaded);
    }

    public function getYamlLoaded()
    {
        $this->__load();
        return parent::getYamlLoaded();
    }

    public function setDate($date)
    {
        $this->__load();
        return parent::setDate($date);
    }

    public function getDate()
    {
        $this->__load();
        return parent::getDate();
    }

    public function setRating($rating)
    {
        $this->__load();
        return parent::setRating($rating);
    }

    public function getRating()
    {
        $this->__load();
        return parent::getRating();
    }

    public function setVotes($votes)
    {
        $this->__load();
        return parent::setVotes($votes);
    }

    public function getVotes()
    {
        $this->__load();
        return parent::getVotes();
    }

    public function setDownloads($downloads)
    {
        $this->__load();
        return parent::setDownloads($downloads);
    }

    public function getDownloads()
    {
        $this->__load();
        return parent::getDownloads();
    }

    public function setPrice($price)
    {
        $this->__load();
        return parent::setPrice($price);
    }

    public function getPrice()
    {
        $this->__load();
        return parent::getPrice();
    }

    public function setCurrency($currency)
    {
        $this->__load();
        return parent::setCurrency($currency);
    }

    public function setMajorVersion($majorVersion)
    {
        $this->__load();
        return parent::setMajorVersion($majorVersion);
    }

    public function getMajorVersion()
    {
        $this->__load();
        return parent::getMajorVersion();
    }

    public function setMinorVersion($minorVersion)
    {
        $this->__load();
        return parent::setMinorVersion($minorVersion);
    }

    public function getMinorVersion()
    {
        $this->__load();
        return parent::getMinorVersion();
    }

    public function setMinorRequiredCoreVersion($minorRequiredCoreVersion)
    {
        $this->__load();
        return parent::setMinorRequiredCoreVersion($minorRequiredCoreVersion);
    }

    public function getMinorRequiredCoreVersion()
    {
        $this->__load();
        return parent::getMinorRequiredCoreVersion();
    }

    public function setRevisionDate($revisionDate)
    {
        $this->__load();
        return parent::setRevisionDate($revisionDate);
    }

    public function getRevisionDate()
    {
        $this->__load();
        return parent::getRevisionDate();
    }

    public function setPackSize($packSize)
    {
        $this->__load();
        return parent::setPackSize($packSize);
    }

    public function getPackSize()
    {
        $this->__load();
        return parent::getPackSize();
    }

    public function setXcnPlan($xcnPlan)
    {
        $this->__load();
        return parent::setXcnPlan($xcnPlan);
    }

    public function getXcnPlan()
    {
        $this->__load();
        return parent::getXcnPlan();
    }

    public function setModuleName($moduleName)
    {
        $this->__load();
        return parent::setModuleName($moduleName);
    }

    public function getModuleName()
    {
        $this->__load();
        return parent::getModuleName();
    }

    public function setAuthorName($authorName)
    {
        $this->__load();
        return parent::setAuthorName($authorName);
    }

    public function getAuthorName()
    {
        $this->__load();
        return parent::getAuthorName();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function setIconURL($iconURL)
    {
        $this->__load();
        return parent::setIconURL($iconURL);
    }

    public function getIconURL()
    {
        $this->__load();
        return parent::getIconURL();
    }

    public function setPageURL($pageURL)
    {
        $this->__load();
        return parent::setPageURL($pageURL);
    }

    public function getPageURL()
    {
        $this->__load();
        return parent::getPageURL();
    }

    public function setAuthorPageURL($authorPageURL)
    {
        $this->__load();
        return parent::setAuthorPageURL($authorPageURL);
    }

    public function getAuthorPageURL()
    {
        $this->__load();
        return parent::getAuthorPageURL();
    }

    public function setDependencies($dependencies)
    {
        $this->__load();
        return parent::setDependencies($dependencies);
    }

    public function getDependencies()
    {
        $this->__load();
        return parent::getDependencies();
    }

    public function setTags($tags)
    {
        $this->__load();
        return parent::setTags($tags);
    }

    public function getTags()
    {
        $this->__load();
        return parent::getTags();
    }

    public function setFromMarketplace($fromMarketplace)
    {
        $this->__load();
        return parent::setFromMarketplace($fromMarketplace);
    }

    public function getFromMarketplace()
    {
        $this->__load();
        return parent::getFromMarketplace();
    }

    public function setIsLanding($isLanding)
    {
        $this->__load();
        return parent::setIsLanding($isLanding);
    }

    public function getIsLanding()
    {
        $this->__load();
        return parent::getIsLanding();
    }

    public function setLandingPosition($landingPosition)
    {
        $this->__load();
        return parent::setLandingPosition($landingPosition);
    }

    public function getLandingPosition()
    {
        $this->__load();
        return parent::getLandingPosition();
    }

    public function setIsSystem($isSystem)
    {
        $this->__load();
        return parent::setIsSystem($isSystem);
    }

    public function getIsSystem()
    {
        $this->__load();
        return parent::getIsSystem();
    }

    public function setHasLicense($hasLicense)
    {
        $this->__load();
        return parent::setHasLicense($hasLicense);
    }

    public function getHasLicense()
    {
        $this->__load();
        return parent::getHasLicense();
    }

    public function setEditionState($editionState)
    {
        $this->__load();
        return parent::setEditionState($editionState);
    }

    public function getEditionState()
    {
        $this->__load();
        return parent::getEditionState();
    }

    public function setEditions($editions)
    {
        $this->__load();
        return parent::setEditions($editions);
    }

    public function getEditions()
    {
        $this->__load();
        return parent::getEditions();
    }

    public function map(array $data)
    {
        $this->__load();
        return parent::map($data);
    }

    public function __get($name)
    {
        $this->__load();
        return parent::__get($name);
    }

    public function __set($name, $value)
    {
        $this->__load();
        return parent::__set($name, $value);
    }

    public function __isset($name)
    {
        $this->__load();
        return parent::__isset($name);
    }

    public function __unset($name)
    {
        $this->__load();
        return parent::__unset($name);
    }

    public function getRepository()
    {
        $this->__load();
        return parent::getRepository();
    }

    public function checkCache()
    {
        $this->__load();
        return parent::checkCache();
    }

    public function detach()
    {
        $this->__load();
        return parent::detach();
    }

    public function __call($method, array $args = array (
))
    {
        $this->__load();
        return parent::__call($method, $args);
    }

    public function setterProperty($property, $value)
    {
        $this->__load();
        return parent::setterProperty($property, $value);
    }

    public function getterProperty($property)
    {
        $this->__load();
        return parent::getterProperty($property);
    }

    public function isPersistent()
    {
        $this->__load();
        return parent::isPersistent();
    }

    public function isDetached()
    {
        $this->__load();
        return parent::isDetached();
    }

    public function getUniqueIdentifierName()
    {
        $this->__load();
        return parent::getUniqueIdentifierName();
    }

    public function getUniqueIdentifier()
    {
        $this->__load();
        return parent::getUniqueIdentifier();
    }

    public function update()
    {
        $this->__load();
        return parent::update();
    }

    public function create()
    {
        $this->__load();
        return parent::create();
    }

    public function delete()
    {
        $this->__load();
        return parent::delete();
    }

    public function processFiles($field, array $data)
    {
        $this->__load();
        return parent::processFiles($field, $data);
    }

    public function cloneEntity()
    {
        $this->__load();
        return parent::cloneEntity();
    }

    public function prepareEntityBeforeCommit($type)
    {
        $this->__load();
        return parent::prepareEntityBeforeCommit($type);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'moduleID', 'name', 'author', 'authorEmail', 'enabled', 'installed', 'yamlLoaded', 'date', 'rating', 'votes', 'downloads', 'price', 'currency', 'majorVersion', 'minorVersion', 'minorRequiredCoreVersion', 'revisionDate', 'packSize', 'xcnPlan', 'moduleName', 'authorName', 'description', 'iconURL', 'pageURL', 'authorPageURL', 'dependencies', 'tags', 'fromMarketplace', 'isLanding', 'landingPosition', 'isSystem', 'hasLicense', 'editionState', 'editions');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}