<?php

namespace XLite\Model\Proxy\__CG__\XLite\Model;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class TemplatePatch extends \XLite\Model\TemplatePatch implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getPatchId()
    {
        $this->__load();
        return parent::getPatchId();
    }

    public function setZone($zone)
    {
        $this->__load();
        return parent::setZone($zone);
    }

    public function getZone()
    {
        $this->__load();
        return parent::getZone();
    }

    public function setLang($lang)
    {
        $this->__load();
        return parent::setLang($lang);
    }

    public function getLang()
    {
        $this->__load();
        return parent::getLang();
    }

    public function setTpl($tpl)
    {
        $this->__load();
        return parent::setTpl($tpl);
    }

    public function getTpl()
    {
        $this->__load();
        return parent::getTpl();
    }

    public function setPatchType($patchType)
    {
        $this->__load();
        return parent::setPatchType($patchType);
    }

    public function getPatchType()
    {
        $this->__load();
        return parent::getPatchType();
    }

    public function setXpathQuery($xpathQuery)
    {
        $this->__load();
        return parent::setXpathQuery($xpathQuery);
    }

    public function getXpathQuery()
    {
        $this->__load();
        return parent::getXpathQuery();
    }

    public function setXpathInsertType($xpathInsertType)
    {
        $this->__load();
        return parent::setXpathInsertType($xpathInsertType);
    }

    public function getXpathInsertType()
    {
        $this->__load();
        return parent::getXpathInsertType();
    }

    public function setXpathBlock($xpathBlock)
    {
        $this->__load();
        return parent::setXpathBlock($xpathBlock);
    }

    public function getXpathBlock()
    {
        $this->__load();
        return parent::getXpathBlock();
    }

    public function setRegexpPattern($regexpPattern)
    {
        $this->__load();
        return parent::setRegexpPattern($regexpPattern);
    }

    public function getRegexpPattern()
    {
        $this->__load();
        return parent::getRegexpPattern();
    }

    public function setRegexpReplace($regexpReplace)
    {
        $this->__load();
        return parent::setRegexpReplace($regexpReplace);
    }

    public function getRegexpReplace()
    {
        $this->__load();
        return parent::getRegexpReplace();
    }

    public function setCustomCallback($customCallback)
    {
        $this->__load();
        return parent::setCustomCallback($customCallback);
    }

    public function getCustomCallback()
    {
        $this->__load();
        return parent::getCustomCallback();
    }

    public function map(array $data)
    {
        $this->__load();
        return parent::map($data);
    }

    public function __get($name)
    {
        $this->__load();
        return parent::__get($name);
    }

    public function __set($name, $value)
    {
        $this->__load();
        return parent::__set($name, $value);
    }

    public function __isset($name)
    {
        $this->__load();
        return parent::__isset($name);
    }

    public function __unset($name)
    {
        $this->__load();
        return parent::__unset($name);
    }

    public function getRepository()
    {
        $this->__load();
        return parent::getRepository();
    }

    public function checkCache()
    {
        $this->__load();
        return parent::checkCache();
    }

    public function detach()
    {
        $this->__load();
        return parent::detach();
    }

    public function __call($method, array $args = array (
))
    {
        $this->__load();
        return parent::__call($method, $args);
    }

    public function setterProperty($property, $value)
    {
        $this->__load();
        return parent::setterProperty($property, $value);
    }

    public function getterProperty($property)
    {
        $this->__load();
        return parent::getterProperty($property);
    }

    public function isPersistent()
    {
        $this->__load();
        return parent::isPersistent();
    }

    public function isDetached()
    {
        $this->__load();
        return parent::isDetached();
    }

    public function getUniqueIdentifierName()
    {
        $this->__load();
        return parent::getUniqueIdentifierName();
    }

    public function getUniqueIdentifier()
    {
        $this->__load();
        return parent::getUniqueIdentifier();
    }

    public function update()
    {
        $this->__load();
        return parent::update();
    }

    public function create()
    {
        $this->__load();
        return parent::create();
    }

    public function delete()
    {
        $this->__load();
        return parent::delete();
    }

    public function processFiles($field, array $data)
    {
        $this->__load();
        return parent::processFiles($field, $data);
    }

    public function cloneEntity()
    {
        $this->__load();
        return parent::cloneEntity();
    }

    public function prepareEntityBeforeCommit($type)
    {
        $this->__load();
        return parent::prepareEntityBeforeCommit($type);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'patch_id', 'zone', 'lang', 'tpl', 'patch_type', 'xpath_query', 'xpath_insert_type', 'xpath_block', 'regexp_pattern', 'regexp_replace', 'custom_callback');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}